services:
  app:
    build: .
    ports:
      - '${PORT:-3333}:${PORT:-3333}'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - app_storage:/app/storage/uploads
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  app_storage:
