import vine from '@vinejs/vine'

export const createProductValidator = vine.create({
  name: vine.string().trim().minLength(3).maxLength(255),
  slug: vine.string().trim().minLength(3).maxLength(255).optional(),
  description: vine.string().trim().minLength(10).optional(),
  shortDescription: vine.string().trim().maxLength(500).optional(),
  category: vine.enum([
    'health_fitness',
    'business_investing',
    'software_saas',
    'ecommerce',
    'education',
    'fashion',
    'beauty',
    'home_garden',
    'technology',
    'finance',
    'digital_services',
    'ai_tools',
    'productivity',
    'lifestyle'
  ] as const),
  productType: vine.enum(['digital', 'physical', 'service'] as const),
  price: vine.number().min(0.01),
  salePrice: vine.number().min(0.01).optional(),
  commissionRate: vine.number().min(0).max(100),
  imageUrl: vine.string().url().optional(),
  galleryUrls: vine.array(vine.string().url()).optional(),
  tags: vine.array(vine.string().trim()).optional(),
  isFeatured: vine.boolean().optional(),
  recurringBilling: vine.boolean().optional(),
  billingCycle: vine.enum(['one_time', 'monthly', 'yearly'] as const).optional(),
  affiliateResources: vine.any().optional(),
})

export const updateProductValidator = vine.create({
  name: vine.string().trim().minLength(3).maxLength(255).optional(),
  slug: vine.string().trim().minLength(3).maxLength(255).optional(),
  description: vine.string().trim().minLength(10).optional(),
  shortDescription: vine.string().trim().maxLength(500).optional(),
  category: vine.enum([
    'health_fitness',
    'business_investing',
    'software_saas',
    'ecommerce',
    'education',
    'fashion',
    'beauty',
    'home_garden',
    'technology',
    'finance',
    'digital_services',
    'ai_tools',
    'productivity',
    'lifestyle'
  ] as const).optional(),
  productType: vine.enum(['digital', 'physical', 'service'] as const).optional(),
  price: vine.number().min(0.01).optional(),
  salePrice: vine.number().min(0.01).optional(),
  commissionRate: vine.number().min(0).max(100).optional(),
  imageUrl: vine.string().url().optional(),
  galleryUrls: vine.array(vine.string().url()).optional(),
  tags: vine.array(vine.string().trim()).optional(),
  isFeatured: vine.boolean().optional(),
  recurringBilling: vine.boolean().optional(),
  billingCycle: vine.enum(['one_time', 'monthly', 'yearly'] as const).optional(),
  affiliateResources: vine.any().optional(),
})
