/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AffiliateLinkSchema extends BaseModel {
  static $columns = [
    'affiliateId',
    'campaignName',
    'clicks',
    'commissionEarned',
    'conversions',
    'createdAt',
    'id',
    'linkCode',
    'productId',
    'productName',
    'revenue',
    'status',
    'subId',
    'updatedAt',
  ] as const
  $columns = AffiliateLinkSchema.$columns
  @column()
  declare affiliateId: number
  @column()
  declare campaignName: string | null
  @column()
  declare clicks: number | null
  @column()
  declare commissionEarned: string | null
  @column()
  declare conversions: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare linkCode: string
  @column()
  declare productId: number
  @column()
  declare productName: string | null
  @column()
  declare revenue: string | null
  @column()
  declare status: string | null
  @column()
  declare subId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BlogPostSchema extends BaseModel {
  static $columns = [
    'authorName',
    'category',
    'content',
    'createdAt',
    'excerpt',
    'featuredImageUrl',
    'id',
    'publishedAt',
    'readTimeMinutes',
    'seoDescription',
    'seoTitle',
    'slug',
    'status',
    'tags',
    'title',
    'updatedAt',
    'viewCount',
  ] as const
  $columns = BlogPostSchema.$columns
  @column()
  declare authorName: string | null
  @column()
  declare category: string | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excerpt: string | null
  @column()
  declare featuredImageUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare readTimeMinutes: number | null
  @column()
  declare seoDescription: string | null
  @column()
  declare seoTitle: string | null
  @column()
  declare slug: string | null
  @column()
  declare status: string | null
  @column()
  declare tags: any | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare viewCount: number | null
}

export class EmailCampaignSchema extends BaseModel {
  static $columns = [
    'audienceSegment',
    'campaignType',
    'clickCount',
    'content',
    'conversionCount',
    'createdAt',
    'id',
    'name',
    'openCount',
    'recipientsCount',
    'revenueGenerated',
    'sentAt',
    'status',
    'subject',
    'updatedAt',
  ] as const
  $columns = EmailCampaignSchema.$columns
  @column()
  declare audienceSegment: string | null
  @column()
  declare campaignType: string | null
  @column()
  declare clickCount: number | null
  @column()
  declare content: string | null
  @column()
  declare conversionCount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare openCount: number | null
  @column()
  declare recipientsCount: number | null
  @column()
  declare revenueGenerated: string | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NewsletterSubscriberSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'id',
    'interests',
    'name',
    'source',
    'status',
    'updatedAt',
  ] as const
  $columns = NewsletterSubscriberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare interests: any | null
  @column()
  declare name: string | null
  @column()
  declare source: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NewsletterSchema extends BaseModel {
  static $columns = [
    'category',
    'clickCount',
    'content',
    'createdAt',
    'id',
    'openCount',
    'recipientsCount',
    'revenueGenerated',
    'sentAt',
    'status',
    'subject',
    'updatedAt',
  ] as const
  $columns = NewsletterSchema.$columns
  @column()
  declare category: string | null
  @column()
  declare clickCount: number | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare openCount: number | null
  @column()
  declare recipientsCount: number | null
  @column()
  declare revenueGenerated: string | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = [
    'affiliateId',
    'affiliateLinkId',
    'amount',
    'buyerEmail',
    'buyerId',
    'commissionAmount',
    'createdAt',
    'currency',
    'id',
    'orderNumber',
    'paymentMethod',
    'platformFee',
    'productId',
    'productName',
    'status',
    'updatedAt',
    'vendorId',
    'vendorPayout',
  ] as const
  $columns = OrderSchema.$columns
  @column()
  declare affiliateId: number | null
  @column()
  declare affiliateLinkId: number | null
  @column()
  declare amount: string
  @column()
  declare buyerEmail: string | null
  @column()
  declare buyerId: number | null
  @column()
  declare commissionAmount: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderNumber: string
  @column()
  declare paymentMethod: string | null
  @column()
  declare platformFee: string | null
  @column()
  declare productId: number | null
  @column()
  declare productName: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vendorId: number | null
  @column()
  declare vendorPayout: string | null
}

export class PaymentGatewayKeySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'gateway',
    'id',
    'isActive',
    'merchantId',
    'publicKey',
    'secretKey',
    'updatedAt',
    'webhookSecret',
  ] as const
  $columns = PaymentGatewayKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gateway: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare merchantId: string | null
  @column()
  declare publicKey: string
  @column()
  declare secretKey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare webhookSecret: string | null
}

export class PayoutRequestSchema extends BaseModel {
  static $columns = [
    'adminNotes',
    'amount',
    'createdAt',
    'id',
    'payoutDetails',
    'payoutMethod',
    'processedAt',
    'status',
    'updatedAt',
    'userId',
    'walletId',
  ] as const
  $columns = PayoutRequestSchema.$columns
  @column()
  declare adminNotes: string | null
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payoutDetails: string
  @column()
  declare payoutMethod: string
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare walletId: number
}

export class ProductSchema extends BaseModel {
  static $columns = [
    'affiliateResources',
    'avgEarningsPerSale',
    'billingCycle',
    'category',
    'commissionRate',
    'conversionRate',
    'createdAt',
    'description',
    'galleryUrls',
    'gravityScore',
    'id',
    'imageUrl',
    'isFeatured',
    'name',
    'price',
    'productType',
    'rating',
    'recurringBilling',
    'refundRate',
    'reviewCount',
    'salePrice',
    'shortDescription',
    'slug',
    'status',
    'tags',
    'totalRevenue',
    'totalSales',
    'updatedAt',
    'vendorId',
    'vendorName',
  ] as const
  $columns = ProductSchema.$columns
  @column()
  declare affiliateResources: any | null
  @column()
  declare avgEarningsPerSale: string | null
  @column()
  declare billingCycle: string | null
  @column()
  declare category: string
  @column()
  declare conversionRate: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare galleryUrls: any | null
  @column()
  declare gravityScore: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare isFeatured: boolean | null
  @column()
  declare name: string
  @column({
    consume: (value: string | number | null) => (value === null ? null : Number(value)),
  })
  declare price: string

  @column({
    consume: (value: string | number | null) => (value === null ? null : Number(value)),
  })
  declare commissionRate: number
  @column()
  declare productType: string
  @column()
  declare rating: string | null
  @column()
  declare recurringBilling: boolean | null
  @column()
  declare refundRate: string | null
  @column()
  declare reviewCount: number | null
  @column()
  declare salePrice: string | null
  @column()
  declare shortDescription: string | null
  @column()
  declare slug: string | null
  @column()
  declare status: string | null
  @column()
  declare tags: any | null
  @column()
  declare totalRevenue: string | null
  @column()
  declare totalSales: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vendorId: number | null
  @column()
  declare vendorName: string | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class ReviewSchema extends BaseModel {
  static $columns = [
    'cons',
    'content',
    'createdAt',
    'helpfulCount',
    'id',
    'isVerifiedPurchase',
    'productId',
    'productName',
    'pros',
    'rating',
    'reviewerName',
    'status',
    'title',
    'updatedAt',
  ] as const
  $columns = ReviewSchema.$columns
  @column()
  declare cons: any | null
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare helpfulCount: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isVerifiedPurchase: boolean | null
  @column()
  declare productId: number
  @column()
  declare productName: string | null
  @column()
  declare pros: any | null
  @column()
  declare rating: number
  @column()
  declare reviewerName: string | null
  @column()
  declare status: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SiteSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'label', 'updatedAt', 'value'] as const
  $columns = SiteSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare label: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'bio',
    'businessDescription',
    'businessLogo',
    'businessName',
    'businessType',
    'country',
    'coverBanner',
    'createdAt',
    'email',
    'emailVerifiedAt',
    'fullName',
    'heardAbout',
    'id',
    'instagram',
    'location',
    'marketingChannels',
    'niche',
    'otpCode',
    'otpExpiresAt',
    'password',
    'payoutDetails',
    'payoutMethod',
    'phone',
    'productCategories',
    'profilePicture',
    'resetToken',
    'resetTokenExpiresAt',
    'role',
    'twitter',
    'updatedAt',
    'website',
    'youtube',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare bio: string | null
  @column()
  declare businessDescription: string | null
  @column()
  declare businessLogo: string | null
  @column()
  declare businessName: string | null
  @column()
  declare businessType: string | null
  @column()
  declare country: string | null
  @column()
  declare coverBanner: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column()
  declare heardAbout: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare instagram: string | null
  @column()
  declare location: string | null
  @column()
  declare marketingChannels: string | null
  @column()
  declare niche: string | null
  @column()
  declare otpCode: string | null
  @column.dateTime()
  declare otpExpiresAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare payoutDetails: string | null
  @column()
  declare payoutMethod: string | null
  @column()
  declare phone: string | null
  @column()
  declare productCategories: string | null
  @column()
  declare profilePicture: string | null
  @column()
  declare resetToken: string | null
  @column.dateTime()
  declare resetTokenExpiresAt: DateTime | null
  @column()
  declare role: string
  @column()
  declare twitter: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare website: string | null
  @column()
  declare youtube: string | null
}

export class WalletTransactionSchema extends BaseModel {
  static $columns = [
    'amount',
    'balanceAfter',
    'category',
    'createdAt',
    'description',
    'id',
    'referenceId',
    'referenceType',
    'type',
    'walletId',
  ] as const
  $columns = WalletTransactionSchema.$columns
  @column()
  declare amount: string
  @column()
  declare balanceAfter: string
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare referenceId: number | null
  @column()
  declare referenceType: string | null
  @column()
  declare type: string
  @column()
  declare walletId: number
}

export class WalletSchema extends BaseModel {
  static $columns = [
    'availableBalance',
    'createdAt',
    'currency',
    'id',
    'pendingBalance',
    'updatedAt',
    'userId',
  ] as const
  $columns = WalletSchema.$columns
  @column()
  declare availableBalance: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pendingBalance: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}
