import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('etsy_shops', (table) => {
      table.increments('id')
      table.integer('vendor_id').unsigned().notNullable().unique()
      table.string('shop_id').notNullable().unique()
      table.string('shop_name').notNullable()
      table.string('shop_url').notNullable().unique()
      table.text('access_token').notNullable()
      table.text('refresh_token').nullable()
      table.string('token_type').defaultTo('Bearer')
      table.integer('expires_in').unsigned().nullable()
      table.json('scopes').defaultTo('[]')
      table.boolean('is_connected').defaultTo(false)
      table.enum('connection_status', ['disconnected', 'connecting', 'connected', 'error']).defaultTo('disconnected')
      table.timestamp('last_sync_at').nullable()
      table.timestamp('last_listings_sync_at').nullable()
      table.timestamp('last_orders_sync_at').nullable()
      table.integer('sync_frequency').unsigned().defaultTo(60)
      table.boolean('auto_sync').defaultTo(true)
      table.integer('total_listings').unsigned().defaultTo(0)
      table.integer('total_orders').unsigned().defaultTo(0)
      table.decimal('total_revenue', 10, 2).defaultTo(0)
      table.string('currency', 3).defaultTo('USD')
      table.integer('shop_response_time_minutes').unsigned().nullable()
      table.decimal('shop_rating', 3, 1).nullable()
      table.integer('followers').unsigned().defaultTo(0)
      table.json('shop_settings').nullable()
      table.json('error_log').nullable()
      table.timestamp('last_error_at').nullable()
      table.string('last_error_message').nullable()
      table.timestamp('connected_at').nullable()
      table.timestamp('disconnected_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('vendor_id').references('id').inTable('users').onDelete('CASCADE')
      table.index('vendor_id')
      table.index('shop_id')
      table.index('connection_status')
    })

    this.schema.createTable('etsy_listings', (table) => {
      table.increments('id')
      table.integer('etsy_shop_id').unsigned().notNullable()
      table.string('listing_id').notNullable()
      table.string('title').notNullable()
      table.text('description').nullable()
      table.decimal('price', 10, 2).notNullable()
      table.string('currency', 3).defaultTo('USD')
      table.integer('quantity').unsigned().defaultTo(0)
      table.string('sku').nullable()
      table.enum('state', ['active', 'inactive', 'sold_out', 'deactivated']).defaultTo('active')
      table.integer('views').unsigned().defaultTo(0)
      table.integer('favorites').unsigned().defaultTo(0)
      table.integer('sales').unsigned().defaultTo(0)
      table.decimal('total_revenue', 10, 2).defaultTo(0)
      table.string('category').nullable()
      table.json('tags').nullable()
      table.json('materials').nullable()
      table.string('image_url').nullable()
      table.json('images').nullable()
      table.decimal('vendor_commission_rate', 5, 2).defaultTo(0)
      table.decimal('affiliate_commission_rate', 5, 2).defaultTo(0)
      table.boolean('synced_to_hub').defaultTo(false)
      table.timestamp('last_synced_at').nullable()
      table.json('raw_data').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('etsy_shop_id').references('id').inTable('etsy_shops').onDelete('CASCADE')
      table.index('etsy_shop_id')
      table.index('listing_id')
      table.index('state')
    })

    this.schema.createTable('etsy_orders', (table) => {
      table.increments('id')
      table.integer('etsy_shop_id').unsigned().notNullable()
      table.string('receipt_id').notNullable().unique()
      table.string('order_number').notNullable()
      table.string('customer_email').nullable()
      table.string('buyer_user_id').nullable()
      table.string('currency', 3).defaultTo('USD')
      table.decimal('total_price', 10, 2).notNullable()
      table.decimal('subtotal_price', 10, 2).notNullable()
      table.decimal('tax_price', 10, 2).defaultTo(0)
      table.decimal('shipping_price', 10, 2).defaultTo(0)
      table.decimal('discount_amount', 10, 2).defaultTo(0)
      table.boolean('affiliate_link_used').defaultTo(false)
      table.integer('affiliate_id').unsigned().nullable()
      table.integer('campaign_id').unsigned().nullable()
      table.timestamp('ordered_at').notNullable()
      table.enum('status', ['pending', 'processing', 'shipped', 'delivered', 'cancelled']).defaultTo('pending')
      table.enum('payment_status', ['pending', 'paid', 'refunded']).defaultTo('pending')
      table.json('line_items').notNullable()
      table.json('shipping_address').nullable()
      table.string('tracking_code').nullable()
      table.timestamp('shipped_at').nullable()
      table.timestamp('delivered_at').nullable()
      table.text('notes').nullable()
      table.boolean('commission_calculated').defaultTo(false)
      table.decimal('commission_amount', 10, 2).defaultTo(0)
      table.decimal('vendor_commission_amount', 10, 2).defaultTo(0)
      table.decimal('affiliate_commission_amount', 10, 2).defaultTo(0)
      table.enum('commission_status', ['pending', 'approved', 'paid', 'cancelled']).defaultTo('pending')
      table.integer('conversion_id').unsigned().nullable()
      table.boolean('is_disputed').defaultTo(false)
      table.string('dispute_reason').nullable()
      table.boolean('synced_to_hub').defaultTo(false)
      table.json('raw_data').nullable()
      table.timestamp('refunded_at').nullable()
      table.decimal('refund_amount', 10, 2).defaultTo(0)
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('etsy_shop_id').references('id').inTable('etsy_shops').onDelete('CASCADE')
      table.index('etsy_shop_id')
      table.index('receipt_id')
      table.index('payment_status')
    })
  }

  async down() {
    this.schema.dropTable('etsy_orders')
    this.schema.dropTable('etsy_listings')
    this.schema.dropTable('etsy_shops')
  }
}
