import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('shopify_stores', (table) => {
      table.increments('id')
      table.integer('vendor_id').unsigned().notNullable().unique()
      table.string('shop_name').notNullable()
      table.string('shop_domain').notNullable().unique()
      table.text('access_token').notNullable()
      table.text('refresh_token').nullable()
      table.string('api_version').defaultTo('2024-01')
      table.json('scopes').defaultTo('[]')
      table.boolean('is_connected').defaultTo(false)
      table.enum('connection_status', ['disconnected', 'connecting', 'connected', 'error']).defaultTo('disconnected')
      table.timestamp('last_sync_at').nullable()
      table.timestamp('last_order_sync_at').nullable()
      table.integer('sync_frequency').unsigned().defaultTo(60)
      table.boolean('auto_sync').defaultTo(true)
      table.integer('total_products').unsigned().defaultTo(0)
      table.integer('total_orders').unsigned().defaultTo(0)
      table.integer('total_revenue').unsigned().defaultTo(0)
      table.string('currency', 3).defaultTo('USD')
      table.string('webhook_id').nullable()
      table.json('store_settings').nullable()
      table.json('error_log').nullable()
      table.timestamp('last_error_at').nullable()
      table.string('last_error_message').nullable()
      table.timestamp('connected_at').nullable()
      table.timestamp('disconnected_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('vendor_id').references('id').inTable('users').onDelete('CASCADE')
      table.index('vendor_id')
      table.index('shop_domain')
      table.index('connection_status')
    })

    this.schema.createTable('shopify_products', (table) => {
      table.increments('id')
      table.integer('shopify_store_id').unsigned().notNullable()
      table.string('shopify_product_id').notNullable()
      table.string('shopify_variant_id').nullable()
      table.string('title').notNullable()
      table.text('description').nullable()
      table.string('sku').nullable()
      table.decimal('price', 10, 2).notNullable()
      table.decimal('compare_at_price', 10, 2).nullable()
      table.string('currency', 3).defaultTo('USD')
      table.integer('inventory_qty').unsigned().defaultTo(0)
      table.decimal('vendor_commission_rate', 5, 2).defaultTo(0)
      table.decimal('affiliate_commission_rate', 5, 2).defaultTo(0)
      table.string('image_url').nullable()
      table.string('shopify_url').notNullable()
      table.enum('status', ['draft', 'active', 'archived']).defaultTo('active')
      table.enum('sync_status', ['pending', 'synced', 'error']).defaultTo('pending')
      table.boolean('is_synced_to_hub').defaultTo(false)
      table.timestamp('last_synced_at').nullable()
      table.integer('total_sales').unsigned().defaultTo(0)
      table.integer('total_affiliate_revenue').unsigned().defaultTo(0)
      table.integer('total_commission_paid').unsigned().defaultTo(0)
      table.decimal('weight', 8, 2).nullable()
      table.string('weight_unit').nullable()
      table.string('variant_title').nullable()
      table.json('collections').nullable()
      table.json('tags').nullable()
      table.json('options').nullable()
      table.text('raw_data').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('shopify_store_id').references('id').inTable('shopify_stores').onDelete('CASCADE')
      table.index('shopify_store_id')
      table.index('shopify_product_id')
      table.index('status')
    })

    this.schema.createTable('shopify_orders', (table) => {
      table.increments('id')
      table.integer('shopify_store_id').unsigned().notNullable()
      table.string('shopify_order_id').notNullable().unique()
      table.string('order_number').notNullable()
      table.string('customer_email').nullable()
      table.string('customer_name').nullable()
      table.string('currency', 3).defaultTo('USD')
      table.decimal('total_price', 10, 2).notNullable()
      table.decimal('subtotal_price', 10, 2).notNullable()
      table.decimal('tax_price', 10, 2).defaultTo(0)
      table.decimal('shipping_price', 10, 2).defaultTo(0)
      table.decimal('discount_amount', 10, 2).defaultTo(0)
      table.boolean('affiliate_link_used').defaultTo(false)
      table.integer('affiliate_id').unsigned().nullable()
      table.integer('campaign_id').unsigned().nullable()
      table.timestamp('ordered_at').notNullable()
      table.enum('fulfillment_status', ['pending', 'partial', 'fulfilled', 'voided', 'cancelled']).defaultTo('pending')
      table.enum('payment_status', ['pending', 'authorized', 'paid', 'refunded', 'voided']).defaultTo('pending')
      table.enum('financial_status', ['pending', 'paid', 'refunded', 'voided', 'partially_paid', 'partially_refunded']).defaultTo('pending')
      table.json('line_items').notNullable()
      table.json('shipping_address').nullable()
      table.json('billing_address').nullable()
      table.text('notes').nullable()
      table.json('tags').nullable()
      table.boolean('commission_calculated').defaultTo(false)
      table.decimal('commission_amount', 10, 2).defaultTo(0)
      table.decimal('vendor_commission_amount', 10, 2).defaultTo(0)
      table.decimal('affiliate_commission_amount', 10, 2).defaultTo(0)
      table.enum('commission_status', ['pending', 'approved', 'paid', 'cancelled']).defaultTo('pending')
      table.integer('conversion_id').unsigned().nullable()
      table.boolean('is_disputed').defaultTo(false)
      table.string('dispute_reason').nullable()
      table.boolean('synced_to_hub').defaultTo(false)
      table.text('raw_data').nullable()
      table.timestamp('refunded_at').nullable()
      table.decimal('refund_amount', 10, 2).defaultTo(0)
      table.boolean('webhook_received').defaultTo(false)
      table.timestamp('last_webhook_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('shopify_store_id').references('id').inTable('shopify_stores').onDelete('CASCADE')
      table.index('shopify_store_id')
      table.index('shopify_order_id')
      table.index('affiliate_id')
      table.index('payment_status')
    })
  }

  async down() {
    this.schema.dropTable('shopify_orders')
    this.schema.dropTable('shopify_products')
    this.schema.dropTable('shopify_stores')
  }
}
