import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('report_configurations', (table) => {
      table.increments('id')
      table.integer('user_id').unsigned().notNullable()
      table.string('name').notNullable()
      table.text('description').nullable()
      table.enum('report_type', ['conversion', 'commission', 'campaign', 'affiliate', 'fraud', 'revenue', 'custom']).notNullable()
      table.enum('format', ['pdf', 'csv', 'excel', 'json']).defaultTo('pdf')
      table.json('filters').nullable()
      table.json('columns').nullable()
      table.json('aggregations').nullable()
      table.enum('frequency', ['once', 'daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'custom']).defaultTo('once')
      table.json('schedule_config').nullable()
      table.string('email_recipients').nullable()
      table.boolean('include_charts').defaultTo(true)
      table.boolean('include_summary').defaultTo(true)
      table.boolean('include_trends').defaultTo(true)
      table.boolean('is_active').defaultTo(true)
      table.boolean('is_template').defaultTo(false)
      table.string('template_name').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('user_id')
      table.index('report_type')
      table.index('is_active')
      table.index('is_template')
    })

    this.schema.createTable('report_schedules', (table) => {
      table.increments('id')
      table.integer('report_configuration_id').unsigned().notNullable()
      table.string('cron_expression').notNullable()
      table.enum('schedule_type', ['cron', 'interval', 'manual']).defaultTo('cron')
      table.integer('interval_minutes').nullable()
      table.datetime('start_date').notNullable()
      table.datetime('end_date').nullable()
      table.integer('max_occurrences').nullable()
      table.integer('occurrences_count').defaultTo(0)
      table.datetime('next_run_at').nullable()
      table.datetime('last_run_at').nullable()
      table.boolean('is_active').defaultTo(true)
      table.boolean('is_paused').defaultTo(false)
      table.integer('retry_count').defaultTo(0)
      table.integer('max_retries').defaultTo(3)
      table.string('last_error_message').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('report_configuration_id')
      table.index('is_active')
      table.index('next_run_at')
    })

    this.schema.createTable('report_logs', (table) => {
      table.increments('id')
      table.integer('report_configuration_id').unsigned().notNullable()
      table.integer('user_id').unsigned().notNullable()
      table.string('report_file_name').nullable()
      table.string('report_file_path').nullable()
      table.string('report_file_url').nullable()
      table.integer('file_size').nullable()
      table.string('mime_type').nullable()
      table.enum('status', ['pending', 'processing', 'completed', 'failed', 'archived']).defaultTo('pending')
      table.enum('format_generated', ['pdf', 'csv', 'excel', 'json']).notNullable()
      table.integer('row_count').nullable()
      table.datetime('start_date').notNullable()
      table.datetime('end_date').notNullable()
      table.json('filters_applied').nullable()
      table.decimal('total_rows', 10, 0).nullable()
      table.decimal('total_value', 15, 2).nullable()
      table.text('error_message').nullable()
      table.integer('generation_time_ms').nullable()
      table.json('metadata').nullable()
      table.string('email_sent_to').nullable()
      table.datetime('email_sent_at').nullable()
      table.boolean('is_archived').defaultTo(false)
      table.datetime('archived_at').nullable()
      table.string('archived_location').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('report_configuration_id')
      table.index('user_id')
      table.index('status')
      table.index('created_at')
      table.index('is_archived')
    })

    this.schema.createTable('scheduled_report_executions', (table) => {
      table.increments('id')
      table.integer('report_schedule_id').unsigned().notNullable()
      table.integer('report_log_id').unsigned().nullable()
      table.enum('execution_status', ['scheduled', 'running', 'completed', 'failed', 'skipped']).defaultTo('scheduled')
      table.datetime('scheduled_for').notNullable()
      table.datetime('executed_at').nullable()
      table.integer('execution_duration_ms').nullable()
      table.string('triggered_by').nullable()
      table.json('execution_context').nullable()
      table.text('failure_reason').nullable()
      table.integer('retry_attempt').defaultTo(0)
      table.datetime('retry_at').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('report_schedule_id')
      table.index('execution_status')
      table.index('scheduled_for')
      table.unique(['report_schedule_id', 'scheduled_for'])
    })

    this.schema.createTable('report_exports', (table) => {
      table.increments('id')
      table.integer('report_log_id').unsigned().notNullable()
      table.integer('user_id').unsigned().notNullable()
      table.enum('export_type', ['manual', 'scheduled', 'bulk']).defaultTo('manual')
      table.string('export_identifier').unique()
      table.boolean('include_headers').defaultTo(true)
      table.json('export_columns').nullable()
      table.integer('total_records').defaultTo(0)
      table.integer('exported_records').defaultTo(0)
      table.decimal('export_file_size', 12, 2).nullable()
      table.string('s3_bucket').nullable()
      table.string('s3_key').nullable()
      table.string('expiration_days').nullable()
      table.boolean('is_encrypted').defaultTo(false)
      table.string('encryption_key').nullable()
      table.json('metadata').nullable()
      table.timestamp('expires_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('report_log_id')
      table.index('user_id')
      table.index('export_type')
    })

    this.schema.createTable('report_archives', (table) => {
      table.increments('id')
      table.integer('report_log_id').unsigned().notNullable()
      table.string('archive_location').notNullable()
      table.string('archive_format').nullable()
      table.integer('original_file_size').nullable()
      table.integer('compressed_file_size').nullable()
      table.decimal('compression_ratio', 5, 2).nullable()
      table.datetime('archived_at').notNullable()
      table.datetime('retention_until').nullable()
      table.boolean('is_retrievable').defaultTo(true)
      table.json('archive_metadata').nullable()
      table.string('storage_type').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('report_log_id')
      table.index('archived_at')
      table.index('retention_until')
    })
  }

  async down() {
    this.schema.dropTable('report_archives')
    this.schema.dropTable('report_exports')
    this.schema.dropTable('scheduled_report_executions')
    this.schema.dropTable('report_logs')
    this.schema.dropTable('report_schedules')
    this.schema.dropTable('report_configurations')
  }
}
