import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('currency_settings', (table) => {
      table.increments('id')
      table.string('currency_code', 3).notNullable().unique()
      table.string('currency_name').notNullable()
      table.string('symbol').notNullable()
      table.decimal('exchange_rate', 12, 6).notNullable().defaultTo(1)
      table.boolean('is_active').defaultTo(true)
      table.boolean('is_base_currency').defaultTo(false)
      table.integer('decimal_places').defaultTo(2)
      table.enum('symbol_position', ['before', 'after']).defaultTo('before')
      table.string('thousands_separator', 5).defaultTo(',')
      table.string('decimal_separator', 5).defaultTo('.')
      table.json('countries').nullable()
      table.json('regions').nullable()
      table.timestamp('last_rate_update_at').nullable()
      table.string('rate_source').nullable()
      table.decimal('min_payment_amount', 10, 2).defaultTo(0)
      table.json('payment_methods').nullable()
      table.decimal('tax_rate', 5, 2).defaultTo(0)
      table.boolean('tax_included').defaultTo(false)
      table.json('banking_details').nullable()
      table.text('notes').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('is_active')
      table.index('is_base_currency')
    })

    this.schema.createTable('currency_exchange_rates', (table) => {
      table.increments('id')
      table.string('from_currency', 3).notNullable()
      table.string('to_currency', 3).notNullable()
      table.decimal('rate', 12, 6).notNullable()
      table.decimal('mid_rate', 12, 6).nullable()
      table.decimal('buy_rate', 12, 6).nullable()
      table.decimal('sell_rate', 12, 6).nullable()
      table.string('source').notNullable()
      table.timestamp('timestamp').notNullable()
      table.timestamp('created_at')
      table.index('from_currency')
      table.index('to_currency')
      table.index('timestamp')
      table.unique(['from_currency', 'to_currency', 'timestamp'])
    })

    this.schema.createTable('regional_pricings', (table) => {
      table.increments('id')
      table.integer('product_id').unsigned().notNullable()
      table.string('region', 5).notNullable()
      table.string('currency', 3).notNullable()
      table.decimal('base_price', 10, 2).notNullable()
      table.decimal('local_price', 10, 2).notNullable()
      table.enum('pricing_strategy', ['fixed', 'percentage', 'dynamic']).defaultTo('fixed')
      table.decimal('adjustment', 10, 2).nullable()
      table.decimal('tax_rate', 5, 2).defaultTo(0)
      table.decimal('discount_rate', 5, 2).nullable()
      table.decimal('shipping_cost', 10, 2).nullable()
      table.boolean('is_active').defaultTo(true)
      table.timestamp('valid_from').notNullable()
      table.timestamp('valid_until').nullable()
      table.decimal('demand_multiplier', 3, 2).defaultTo(1)
      table.json('competitor_pricing').nullable()
      table.text('notes').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('product_id')
      table.index('region')
      table.index('currency')
      table.index('is_active')
    })
  }

  async down() {
    this.schema.dropTable('regional_pricings')
    this.schema.dropTable('currency_exchange_rates')
    this.schema.dropTable('currency_settings')
  }
}
