import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('commission_disputes', (table) => {
      table.increments('id')
      table.integer('commission_ledger_id').unsigned().notNullable()
      table.integer('user_id').unsigned().notNullable()
      table.integer('filed_by_user_id').unsigned().notNullable()
      table.enum('dispute_type', ['amount_mismatch', 'calculation_error', 'missing_commission', 'duplicate_entry', 'payment_issue', 'other']).notNullable()
      table.string('status').defaultTo('open')
      table.enum('priority', ['low', 'medium', 'high', 'critical']).defaultTo('medium')
      table.text('description').notNullable()
      table.text('supporting_notes').nullable()
      table.decimal('disputed_amount', 12, 2).notNullable()
      table.decimal('claimed_amount', 12, 2).nullable()
      table.enum('resolution_type', ['rejection', 'adjustment', 'reversal', 'manual_approval', 'pending']).defaultTo('pending')
      table.decimal('resolved_amount', 12, 2).nullable()
      table.text('resolution_notes').nullable()
      table.integer('resolved_by_user_id').nullable()
      table.datetime('resolved_at').nullable()
      table.datetime('due_date').nullable()
      table.boolean('is_escalated').defaultTo(false)
      table.datetime('escalated_at').nullable()
      table.integer('escalated_to_user_id').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('commission_ledger_id')
      table.index('user_id')
      table.index('filed_by_user_id')
      table.index('status')
      table.index('priority')
      table.index('is_escalated')
    })

    this.schema.createTable('dispute_activities', (table) => {
      table.increments('id')
      table.integer('dispute_id').unsigned().notNullable()
      table.integer('user_id').unsigned().notNullable()
      table.enum('activity_type', ['created', 'status_changed', 'comment_added', 'amount_updated', 'assigned', 'escalated', 'resolved']).notNullable()
      table.string('old_value').nullable()
      table.string('new_value').nullable()
      table.text('description').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.index('dispute_id')
      table.index('user_id')
      table.index('activity_type')
    })

    this.schema.createTable('dispute_comments', (table) => {
      table.increments('id')
      table.integer('dispute_id').unsigned().notNullable()
      table.integer('user_id').unsigned().notNullable()
      table.text('comment').notNullable()
      table.boolean('is_internal').defaultTo(false)
      table.json('attachments').nullable()
      table.integer('parent_comment_id').unsigned().nullable()
      table.boolean('is_edited').defaultTo(false)
      table.datetime('edited_at').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('dispute_id')
      table.index('user_id')
      table.index('is_internal')
    })

    this.schema.createTable('dispute_assignments', (table) => {
      table.increments('id')
      table.integer('dispute_id').unsigned().notNullable()
      table.integer('assigned_to_user_id').unsigned().notNullable()
      table.integer('assigned_by_user_id').unsigned().notNullable()
      table.text('assignment_notes').nullable()
      table.boolean('is_active').defaultTo(true)
      table.datetime('assigned_at').notNullable()
      table.datetime('unassigned_at').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('dispute_id')
      table.index('assigned_to_user_id')
      table.index('is_active')
    })

    this.schema.createTable('dispute_approvals', (table) => {
      table.increments('id')
      table.integer('dispute_id').unsigned().notNullable()
      table.integer('requested_by_user_id').unsigned().notNullable()
      table.integer('approved_by_user_id').unsigned().nullable()
      table.enum('approval_status', ['pending', 'approved', 'rejected']).defaultTo('pending')
      table.text('approval_reason').nullable()
      table.text('rejection_reason').nullable()
      table.datetime('approved_at').nullable()
      table.datetime('rejected_at').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('dispute_id')
      table.index('approval_status')
    })

    this.schema.createTable('dispute_templates', (table) => {
      table.increments('id')
      table.integer('admin_id').unsigned().notNullable()
      table.string('name').notNullable()
      table.text('description').nullable()
      table.enum('dispute_type', ['amount_mismatch', 'calculation_error', 'missing_commission', 'duplicate_entry', 'payment_issue', 'other']).notNullable()
      table.text('resolution_template').nullable()
      table.json('metadata').nullable()
      table.boolean('is_active').defaultTo(true)
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('dispute_type')
      table.index('is_active')
    })

    this.schema.createTable('dispute_statistics', (table) => {
      table.increments('id')
      table.integer('user_id').unsigned().nullable()
      table.integer('total_disputes').defaultTo(0)
      table.integer('open_disputes').defaultTo(0)
      table.integer('resolved_disputes').defaultTo(0)
      table.integer('escalated_disputes').defaultTo(0)
      table.decimal('total_disputed_amount', 15, 2).defaultTo(0)
      table.decimal('total_resolved_amount', 15, 2).defaultTo(0)
      table.decimal('average_resolution_time_days', 8, 2).defaultTo(0)
      table.json('disputes_by_type').nullable()
      table.json('disputes_by_status').nullable()
      table.datetime('last_updated_at').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('user_id')
    })
  }

  async down() {
    this.schema.dropTable('dispute_statistics')
    this.schema.dropTable('dispute_templates')
    this.schema.dropTable('dispute_approvals')
    this.schema.dropTable('dispute_assignments')
    this.schema.dropTable('dispute_comments')
    this.schema.dropTable('dispute_activities')
    this.schema.dropTable('commission_disputes')
  }
}
