import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('affiliate_wallets', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable().unique()
      table.decimal('available_balance', 15, 2).defaultTo(0)
      table.decimal('pending_balance', 15, 2).defaultTo(0)
      table.decimal('total_earned', 15, 2).defaultTo(0)
      table.decimal('total_paid', 15, 2).defaultTo(0)
      table.decimal('minimum_payout_threshold', 15, 2).defaultTo(10)
      table.enum('currency', ['USD', 'GBP', 'EUR', 'NGN', 'KES', 'ZAR']).defaultTo('USD')
      table.datetime('last_payout_at').nullable()
      table.datetime('created_at').notNullable()
      table.datetime('updated_at').notNullable()
      table.index('affiliate_id')
    })

    this.schema.createTable('payout_requests', (table) => {
      table.increments('id')
      table.string('request_id').unique().notNullable()
      table.integer('affiliate_id').unsigned().notNullable()
      table.decimal('amount', 15, 2).notNullable()
      table.enum('status', ['pending', 'approved', 'processing', 'completed', 'failed', 'cancelled']).defaultTo('pending')
      table.enum('payment_method', ['bank_transfer', 'paypal', 'stripe', 'mobile_money', 'crypto']).notNullable()
      table.string('payment_method_id').nullable()
      table.enum('currency', ['USD', 'GBP', 'EUR', 'NGN', 'KES', 'ZAR']).defaultTo('USD')
      table.decimal('platform_fee', 15, 2).defaultTo(0)
      table.decimal('net_amount', 15, 2).notNullable()
      table.string('reference_number').nullable()
      table.text('notes').nullable()
      table.text('rejection_reason').nullable()
      table.datetime('approved_at').nullable()
      table.datetime('processed_at').nullable()
      table.datetime('completed_at').nullable()
      table.datetime('failed_at').nullable()
      table.integer('approved_by_admin_id').unsigned().nullable()
      table.json('metadata').nullable()
      table.datetime('created_at').notNullable()
      table.datetime('updated_at').notNullable()
      table.index('request_id')
      table.index('affiliate_id')
      table.index('status')
      table.index('created_at')
      table.index('approved_at')
      table.index('completed_at')
    })

    this.schema.createTable('payout_methods', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable()
      table.string('method_id').unique().notNullable()
      table.enum('method_type', ['bank_transfer', 'paypal', 'stripe', 'mobile_money', 'crypto']).notNullable()
      table.string('account_holder_name').notNullable()
      table.string('account_number').nullable()
      table.string('bank_code').nullable()
      table.string('bank_name').nullable()
      table.string('country_code').nullable()
      table.string('email').nullable()
      table.string('phone_number').nullable()
      table.string('wallet_address').nullable()
      table.boolean('is_primary').defaultTo(false)
      table.boolean('is_verified').defaultTo(false)
      table.datetime('verified_at').nullable()
      table.json('metadata').nullable()
      table.datetime('created_at').notNullable()
      table.datetime('updated_at').notNullable()
      table.index('affiliate_id')
      table.index('method_type')
    })

    this.schema.createTable('payout_histories', (table) => {
      table.increments('id')
      table.integer('payout_request_id').unsigned().notNullable()
      table.integer('affiliate_id').unsigned().notNullable()
      table.enum('event', ['created', 'approved', 'processing', 'completed', 'failed', 'cancelled']).notNullable()
      table.string('status').notNullable()
      table.text('notes').nullable()
      table.integer('created_by_user_id').unsigned().nullable()
      table.json('metadata').nullable()
      table.datetime('created_at').notNullable()
      table.index('payout_request_id')
      table.index('affiliate_id')
      table.index('event')
      table.index('created_at')
    })
  }

  async down() {
    this.schema.dropTable('payout_histories')
    this.schema.dropTable('payout_methods')
    this.schema.dropTable('payout_requests')
    this.schema.dropTable('affiliate_wallets')
  }
}
