import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('affiliate_links', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable()
      table.integer('campaign_id').unsigned().notNullable()
      table.string('slug').notNullable().unique()
      table.string('token').notNullable().unique()
      table.string('custom_alias').nullable()
      table.text('description').nullable()
      table.datetime('created_at').notNullable()
      table.datetime('updated_at').notNullable()
      table.datetime('expires_at').nullable()
      table.integer('total_clicks').defaultTo(0)
      table.integer('total_conversions').defaultTo(0)
      table.decimal('total_earnings', 12, 2).defaultTo(0)
      table.boolean('is_active').defaultTo(true)
      table.index('affiliate_id')
      table.index('campaign_id')
      table.index('slug')
      table.index('token')
      table.unique(['affiliate_id', 'campaign_id'])
    })

    this.schema.createTable('clicks', (table) => {
      table.increments('id')
      table.string('click_id').unique().notNullable()
      table.integer('affiliate_link_id').unsigned().notNullable()
      table.integer('affiliate_id').unsigned().notNullable()
      table.integer('campaign_id').unsigned().notNullable()
      table.string('user_agent').nullable()
      table.string('ip_address').nullable()
      table.string('referrer').nullable()
      table.string('device_type').nullable()
      table.string('browser').nullable()
      table.string('os').nullable()
      table.string('country').nullable()
      table.string('city').nullable()
      table.json('metadata').nullable()
      table.datetime('clicked_at').notNullable()
      table.datetime('created_at').notNullable()
      table.index('click_id')
      table.index('affiliate_link_id')
      table.index('affiliate_id')
      table.index('campaign_id')
      table.index('clicked_at')
      table.index(['affiliate_id', 'campaign_id'])
    })

    this.schema.createTable('conversions', (table) => {
      table.increments('id')
      table.string('conversion_id').unique().notNullable()
      table.integer('click_id').unsigned().nullable()
      table.integer('affiliate_link_id').unsigned().notNullable()
      table.integer('affiliate_id').unsigned().notNullable()
      table.integer('campaign_id').unsigned().notNullable()
      table.enum('status', ['pending', 'approved', 'rejected', 'reversed']).defaultTo('pending')
      table.decimal('order_value', 15, 2).nullable()
      table.decimal('commission_amount', 12, 2).nullable()
      table.string('external_order_id').nullable()
      table.string('external_conversion_id').nullable()
      table.text('rejection_reason').nullable()
      table.datetime('converted_at').notNullable()
      table.datetime('approved_at').nullable()
      table.datetime('rejected_at').nullable()
      table.datetime('reversed_at').nullable()
      table.integer('approved_by_admin_id').unsigned().nullable()
      table.json('metadata').nullable()
      table.datetime('created_at').notNullable()
      table.datetime('updated_at').notNullable()
      table.index('conversion_id')
      table.index('click_id')
      table.index('affiliate_link_id')
      table.index('affiliate_id')
      table.index('campaign_id')
      table.index('status')
      table.index('converted_at')
      table.index(['affiliate_id', 'campaign_id'])
    })
  }

  async down() {
    this.schema.dropTable('conversions')
    this.schema.dropTable('clicks')
    this.schema.dropTable('affiliate_links')
  }
}
