import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('campaigns', (table) => {
      table.increments('id')
      table.integer('vendor_id').unsigned().notNullable()
      table.string('name').notNullable()
      table.string('product_service_name').notNullable()
      table.text('description').notNullable()
      table.string('image_url').nullable()
      table.string('category').notNullable()
      table.enum('status', ['draft', 'pending_approval', 'active', 'paused', 'completed', 'rejected']).defaultTo('draft')
      table.enum('commission_type', ['percentage', 'fixed_amount', 'lead', 'hybrid']).notNullable()
      table.decimal('commission_amount', 10, 2).notNullable()
      table.string('purchase_destination').notNullable()
      table.integer('attribution_window_days').defaultTo(30)
      table.text('campaign_terms').nullable()
      table.text('promotional_guidelines').nullable()
      table.datetime('start_date').notNullable()
      table.datetime('end_date').nullable()
      table.string('target_audience').nullable()
      table.text('minimum_requirements_for_affiliates').nullable()
      table.text('approval_requirements').nullable()
      table.integer('total_clicks').defaultTo(0)
      table.integer('total_conversions').defaultTo(0)
      table.decimal('total_revenue', 15, 2).defaultTo(0)
      table.decimal('total_commission', 12, 2).defaultTo(0)
      table.integer('active_affiliates').defaultTo(0)
      table.decimal('average_conversion_rate', 5, 2).defaultTo(0)
      table.text('rejection_reason').nullable()
      table.integer('rejected_by_admin_id').unsigned().nullable()
      table.datetime('rejected_at').nullable()
      table.integer('approved_by_admin_id').unsigned().nullable()
      table.datetime('approved_at').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('vendor_id')
      table.index('status')
      table.index('category')
      table.index('start_date')
      table.index('end_date')
    })

    this.schema.createTable('affiliate_campaigns', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable()
      table.integer('campaign_id').unsigned().notNullable()
      table.enum('status', ['joined', 'active', 'paused', 'left']).defaultTo('joined')
      table.integer('clicks').defaultTo(0)
      table.integer('conversions').defaultTo(0)
      table.decimal('conversion_rate', 5, 2).defaultTo(0)
      table.decimal('earnings', 12, 2).defaultTo(0)
      table.datetime('joined_at').notNullable()
      table.datetime('left_at').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('affiliate_id')
      table.index('campaign_id')
      table.index('status')
      table.unique(['affiliate_id', 'campaign_id'])
    })
  }

  async down() {
    this.schema.dropTable('affiliate_campaigns')
    this.schema.dropTable('campaigns')
  }
}
