import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('woocommerce_stores', (table) => {
      table.increments('id')
      table.integer('vendor_id').unsigned().notNullable().unique()
      table.string('store_name').notNullable()
      table.string('store_url').notNullable().unique()
      table.text('consumer_key').notNullable()
      table.text('consumer_secret').notNullable()
      table.string('api_version').defaultTo('wc/v3')
      table.boolean('is_connected').defaultTo(false)
      table.enum('connection_status', ['disconnected', 'connecting', 'connected', 'error']).defaultTo('disconnected')
      table.timestamp('last_sync_at').nullable()
      table.timestamp('last_product_sync_at').nullable()
      table.timestamp('last_order_sync_at').nullable()
      table.integer('sync_frequency').unsigned().defaultTo(60)
      table.boolean('auto_sync').defaultTo(true)
      table.integer('total_products').unsigned().defaultTo(0)
      table.integer('total_orders').unsigned().defaultTo(0)
      table.integer('total_revenue').unsigned().defaultTo(0)
      table.string('currency', 3).defaultTo('USD')
      table.string('webhook_secret').nullable()
      table.string('webhook_url').nullable()
      table.json('store_settings').nullable()
      table.json('error_log').nullable()
      table.timestamp('last_error_at').nullable()
      table.string('last_error_message').nullable()
      table.timestamp('connected_at').nullable()
      table.timestamp('disconnected_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('vendor_id').references('id').inTable('users').onDelete('CASCADE')
      table.index('vendor_id')
      table.index('store_url')
      table.index('connection_status')
    })

    this.schema.createTable('woocommerce_products', (table) => {
      table.increments('id')
      table.integer('woocommerce_store_id').unsigned().notNullable()
      table.integer('woo_product_id').notNullable()
      table.string('title').notNullable()
      table.text('description').nullable()
      table.string('sku').nullable()
      table.decimal('price', 10, 2).notNullable()
      table.decimal('regular_price', 10, 2).nullable()
      table.decimal('sale_price', 10, 2).nullable()
      table.string('currency', 3).defaultTo('USD')
      table.integer('stock_qty').unsigned().defaultTo(0)
      table.decimal('vendor_commission_rate', 5, 2).defaultTo(0)
      table.decimal('affiliate_commission_rate', 5, 2).defaultTo(0)
      table.string('image_url').nullable()
      table.string('product_url').notNullable()
      table.enum('status', ['draft', 'pending', 'private', 'publish']).defaultTo('publish')
      table.enum('sync_status', ['pending', 'synced', 'error']).defaultTo('pending')
      table.boolean('is_synced_to_hub').defaultTo(false)
      table.timestamp('last_synced_at').nullable()
      table.integer('total_sales').unsigned().defaultTo(0)
      table.integer('total_affiliate_revenue').unsigned().defaultTo(0)
      table.integer('total_commission_paid').unsigned().defaultTo(0)
      table.decimal('weight', 8, 2).nullable()
      table.json('dimensions').nullable()
      table.json('categories').nullable()
      table.json('tags').nullable()
      table.json('attributes').nullable()
      table.json('variations').nullable()
      table.text('raw_data').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('woocommerce_store_id').references('id').inTable('woocommerce_stores').onDelete('CASCADE')
      table.index('woocommerce_store_id')
      table.index('woo_product_id')
      table.index('status')
    })

    this.schema.createTable('woocommerce_orders', (table) => {
      table.increments('id')
      table.integer('woocommerce_store_id').unsigned().notNullable()
      table.integer('woo_order_id').notNullable().unique()
      table.string('order_number').notNullable()
      table.string('customer_email').nullable()
      table.string('customer_name').nullable()
      table.string('currency', 3).defaultTo('USD')
      table.decimal('total_price', 10, 2).notNullable()
      table.decimal('subtotal_price', 10, 2).notNullable()
      table.decimal('tax_price', 10, 2).defaultTo(0)
      table.decimal('shipping_price', 10, 2).defaultTo(0)
      table.decimal('discount_amount', 10, 2).defaultTo(0)
      table.boolean('affiliate_link_used').defaultTo(false)
      table.integer('affiliate_id').unsigned().nullable()
      table.integer('campaign_id').unsigned().nullable()
      table.timestamp('ordered_at').notNullable()
      table.enum('status', ['pending', 'processing', 'on-hold', 'completed', 'cancelled', 'refunded']).defaultTo('pending')
      table.string('payment_method').nullable()
      table.enum('payment_status', ['pending', 'paid', 'refunded', 'failed']).defaultTo('pending')
      table.json('line_items').notNullable()
      table.json('shipping_address').nullable()
      table.json('billing_address').nullable()
      table.text('notes').nullable()
      table.boolean('commission_calculated').defaultTo(false)
      table.decimal('commission_amount', 10, 2).defaultTo(0)
      table.decimal('vendor_commission_amount', 10, 2).defaultTo(0)
      table.decimal('affiliate_commission_amount', 10, 2).defaultTo(0)
      table.enum('commission_status', ['pending', 'approved', 'paid', 'cancelled']).defaultTo('pending')
      table.integer('conversion_id').unsigned().nullable()
      table.boolean('is_disputed').defaultTo(false)
      table.string('dispute_reason').nullable()
      table.boolean('synced_to_hub').defaultTo(false)
      table.text('raw_data').nullable()
      table.timestamp('refunded_at').nullable()
      table.decimal('refund_amount', 10, 2).defaultTo(0)
      table.boolean('webhook_received').defaultTo(false)
      table.timestamp('last_webhook_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('woocommerce_store_id').references('id').inTable('woocommerce_stores').onDelete('CASCADE')
      table.index('woocommerce_store_id')
      table.index('woo_order_id')
      table.index('affiliate_id')
      table.index('payment_status')
    })
  }

  async down() {
    this.schema.dropTable('woocommerce_orders')
    this.schema.dropTable('woocommerce_products')
    this.schema.dropTable('woocommerce_stores')
  }
}
