import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('influencer_profiles', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable().unique()
      table.string('display_name').notNullable()
      table.text('bio').nullable()
      table.string('profile_image_url').nullable()
      table.string('category').notNullable()
      table.string('niche').nullable()
      table.integer('follower_count').unsigned().defaultTo(0)
      table.decimal('engagement_rate', 5, 2).defaultTo(0)
      table.json('platforms').defaultTo('{}')
      table.json('platform_followers').defaultTo('{}')
      table.enum('verification_status', ['unverified', 'pending', 'verified', 'suspended']).defaultTo('unverified')
      table.json('verification_documents').nullable()
      table.integer('revenue_30_days').unsigned().defaultTo(0)
      table.integer('revenue_90_days').unsigned().defaultTo(0)
      table.integer('total_revenue').unsigned().defaultTo(0)
      table.decimal('average_commission_rate', 5, 2).defaultTo(0)
      table.string('top_product').nullable()
      table.decimal('conversion_rate', 5, 2).defaultTo(0)
      table.json('audience_demographics').nullable()
      table.string('banner_image_url').nullable()
      table.string('website').nullable()
      table.string('email').nullable()
      table.string('phone').nullable()
      table.string('country_code', 2).nullable()
      table.boolean('is_approved').defaultTo(false)
      table.timestamp('approved_at').nullable()
      table.integer('approved_by').unsigned().nullable()
      table.string('rejection_reason').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('affiliate_id')
      table.index('verification_status')
      table.index('category')
    })

    this.schema.createTable('collaboration_agreements', (table) => {
      table.increments('id')
      table.integer('influencer_id').unsigned().notNullable()
      table.integer('campaign_id').unsigned().notNullable()
      table.integer('vendor_id').unsigned().notNullable()
      table.string('title').notNullable()
      table.text('description').nullable()
      table.enum('status', ['draft', 'proposed', 'accepted', 'active', 'completed', 'cancelled']).defaultTo('draft')
      table.json('commission_structure').notNullable()
      table.decimal('base_commission_rate', 5, 2).notNullable()
      table.json('bonus_structure').nullable()
      table.json('performance_targets').nullable()
      table.boolean('exclusivity_clause').defaultTo(false)
      table.json('exclusive_categories').nullable()
      table.json('content_requirements').nullable()
      table.string('payment_terms').defaultTo('monthly')
      table.integer('minimum_payout').unsigned().defaultTo(0)
      table.timestamp('start_date').notNullable()
      table.timestamp('end_date').nullable()
      table.boolean('auto_renewal').defaultTo(false)
      table.integer('renewal_term_days').unsigned().nullable()
      table.integer('total_earnings').unsigned().defaultTo(0)
      table.integer('total_conversions').unsigned().defaultTo(0)
      table.integer('total_clicks').unsigned().defaultTo(0)
      table.decimal('avg_order_value', 10, 2).defaultTo(0)
      table.decimal('conversion_rate', 5, 2).defaultTo(0)
      table.string('agreement_document').nullable()
      table.text('notes').nullable()
      table.integer('proposed_by').unsigned().notNullable()
      table.timestamp('proposed_at').notNullable()
      table.timestamp('accepted_at').nullable()
      table.integer('accepted_by').unsigned().nullable()
      table.timestamp('completed_at').nullable()
      table.timestamp('cancelled_at').nullable()
      table.string('cancellation_reason').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('influencer_id').references('id').inTable('influencer_profiles').onDelete('CASCADE')
      table.foreign('campaign_id').references('id').inTable('campaigns').onDelete('CASCADE')
      table.foreign('vendor_id').references('id').inTable('users').onDelete('CASCADE')
      table.index('influencer_id')
      table.index('campaign_id')
      table.index('status')
    })

    this.schema.createTable('influencer_contents', (table) => {
      table.increments('id')
      table.integer('influencer_id').unsigned().notNullable()
      table.integer('campaign_id').unsigned().nullable()
      table.string('title').notNullable()
      table.text('description').nullable()
      table.enum('content_type', ['post', 'reel', 'story', 'video', 'article', 'live']).notNullable()
      table.string('platform').notNullable()
      table.string('content_url').notNullable()
      table.string('thumbnail_url').nullable()
      table.string('affiliate_link').nullable()
      table.enum('status', ['draft', 'scheduled', 'published', 'archived']).defaultTo('draft')
      table.timestamp('published_at').nullable()
      table.integer('views').unsigned().defaultTo(0)
      table.integer('likes').unsigned().defaultTo(0)
      table.integer('comments').unsigned().defaultTo(0)
      table.integer('shares').unsigned().defaultTo(0)
      table.decimal('engagement_rate', 5, 2).defaultTo(0)
      table.integer('clicks').unsigned().defaultTo(0)
      table.integer('conversions').unsigned().defaultTo(0)
      table.integer('revenue').unsigned().defaultTo(0)
      table.json('hashtags').nullable()
      table.json('mentions').nullable()
      table.json('linked_products').nullable()
      table.json('media_assets').nullable()
      table.json('performance_metrics').nullable()
      table.enum('approval_status', ['pending', 'approved', 'rejected']).defaultTo('pending')
      table.string('approval_notes').nullable()
      table.string('rejection_reason').nullable()
      table.boolean('is_paid').defaultTo(false)
      table.integer('paid_amount').unsigned().defaultTo(0)
      table.enum('payment_status', ['pending', 'processing', 'paid', 'failed']).defaultTo('pending')
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('influencer_id').references('id').inTable('influencer_profiles').onDelete('CASCADE')
      table.foreign('campaign_id').references('id').inTable('campaigns').onDelete('SET NULL')
      table.index('influencer_id')
      table.index('campaign_id')
      table.index('status')
      table.index('approval_status')
    })
  }

  async down() {
    this.schema.dropTable('influencer_contents')
    this.schema.dropTable('collaboration_agreements')
    this.schema.dropTable('influencer_profiles')
  }
}
