import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('affiliate_profiles', (table) => {
      table.increments('id')
      table.integer('user_id').unsigned().notNullable().unique()
      table.enum('affiliate_tier', ['bronze', 'silver', 'gold', 'platinum']).defaultTo('bronze')
      table.enum('recruitment_source', ['organic', 'referral', 'campaign', 'admin_invited', 'partnership']).notNullable()
      table.text('bio').nullable()
      table.json('specializations').nullable()
      table.json('target_audiences').nullable()
      table.decimal('average_conversion_rate', 5, 2).defaultTo(0)
      table.integer('total_referrals').defaultTo(0)
      table.integer('active_referrals').defaultTo(0)
      table.decimal('total_earnings', 15, 2).defaultTo(0)
      table.integer('months_active').defaultTo(0)
      table.integer('verification_score').defaultTo(0)
      table.boolean('is_verified').defaultTo(false)
      table.boolean('is_approved').defaultTo(false)
      table.boolean('is_suspended').defaultTo(false)
      table.text('suspension_reason').nullable()
      table.datetime('approved_at').nullable()
      table.datetime('suspended_at').nullable()
      table.datetime('verified_at').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('user_id')
      table.index('affiliate_tier')
      table.index('is_verified')
      table.index('is_approved')
    })

    this.schema.createTable('referral_codes', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable()
      table.string('code').unique().notNullable()
      table.text('description').nullable()
      table.integer('max_uses').nullable()
      table.integer('current_uses').defaultTo(0)
      table.decimal('commission_rate_override', 5, 2).nullable()
      table.enum('code_type', ['personal', 'campaign', 'seasonal', 'promotional']).defaultTo('personal')
      table.boolean('is_active').defaultTo(true)
      table.datetime('expires_at').nullable()
      table.datetime('started_at').notNullable()
      table.integer('total_conversions').defaultTo(0)
      table.decimal('total_revenue', 15, 2).defaultTo(0)
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('affiliate_id')
      table.index('code')
      table.index('is_active')
    })

    this.schema.createTable('affiliate_referrals', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable()
      table.integer('referred_user_id').unsigned().notNullable()
      table.integer('referral_code_id').unsigned().nullable()
      table.enum('referral_status', ['pending', 'active', 'inactive', 'converted']).defaultTo('pending')
      table.datetime('activated_at').nullable()
      table.datetime('inactive_at').nullable()
      table.decimal('earned_commission', 12, 2).defaultTo(0)
      table.integer('total_conversions').defaultTo(0)
      table.decimal('total_revenue', 15, 2).defaultTo(0)
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('affiliate_id')
      table.index('referred_user_id')
      table.index('referral_status')
    })

    this.schema.createTable('recruitment_campaigns', (table) => {
      table.increments('id')
      table.integer('admin_id').unsigned().notNullable()
      table.string('name').notNullable()
      table.text('description').nullable()
      table.enum('campaign_type', ['mass_invite', 'tier_promotion', 'seasonal', 'performance_based']).notNullable()
      table.enum('status', ['planning', 'active', 'paused', 'completed']).defaultTo('planning')
      table.decimal('target_affiliates', 10, 0).nullable()
      table.decimal('recruited_count', 10, 0).defaultTo(0)
      table.decimal('conversion_target', 5, 2).nullable()
      table.decimal('bonus_commission_rate', 5, 2).nullable()
      table.datetime('started_at').nullable()
      table.datetime('ended_at').nullable()
      table.decimal('total_bonus_paid', 15, 2).defaultTo(0)
      table.json('target_criteria').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('admin_id')
      table.index('status')
    })

    this.schema.createTable('affiliate_tiers', (table) => {
      table.increments('id')
      table.enum('tier_level', ['bronze', 'silver', 'gold', 'platinum']).unique().notNullable()
      table.decimal('monthly_earning_threshold', 15, 2).notNullable()
      table.integer('minimum_active_referrals').notNullable()
      table.decimal('conversion_rate_minimum', 5, 2).notNullable()
      table.decimal('commission_rate_bonus', 5, 2).defaultTo(0)
      table.json('benefits').nullable()
      table.json('requirements').nullable()
      table.text('description').nullable()
      table.boolean('is_active').defaultTo(true)
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
    })

    this.schema.createTable('tier_promotions', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable()
      table.enum('from_tier', ['bronze', 'silver', 'gold', 'platinum']).notNullable()
      table.enum('to_tier', ['bronze', 'silver', 'gold', 'platinum']).notNullable()
      table.text('promotion_reason').nullable()
      table.boolean('is_automatic').defaultTo(false)
      table.boolean('is_approved').defaultTo(false)
      table.integer('approved_by_user_id').unsigned().nullable()
      table.datetime('approved_at').nullable()
      table.decimal('bonus_commission', 12, 2).nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('affiliate_id')
    })

    this.schema.createTable('affiliate_rewards', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable()
      table.enum('reward_type', ['performance_bonus', 'referral_bonus', 'achievement', 'milestone', 'promotional']).notNullable()
      table.string('reward_name').notNullable()
      table.text('description').nullable()
      table.decimal('reward_amount', 12, 2).notNullable()
      table.enum('status', ['pending', 'awarded', 'claimed', 'expired']).defaultTo('pending')
      table.datetime('earned_at').notNullable()
      table.datetime('awarded_at').nullable()
      table.datetime('claimed_at').nullable()
      table.datetime('expires_at').nullable()
      table.text('earning_criteria').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('affiliate_id')
      table.index('status')
    })

    this.schema.createTable('recruitment_metrics', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().nullable()
      table.integer('campaign_id').unsigned().nullable()
      table.integer('total_recruited').defaultTo(0)
      table.integer('active_recruited').defaultTo(0)
      table.integer('inactive_recruited').defaultTo(0)
      table.decimal('total_referral_earnings', 15, 2).defaultTo(0)
      table.decimal('average_referral_earnings', 12, 2).defaultTo(0)
      table.decimal('conversion_rate', 5, 2).defaultTo(0)
      table.integer('top_performer_count').defaultTo(0)
      table.integer('retention_rate').defaultTo(0)
      table.datetime('last_calculated_at').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('affiliate_id')
      table.index('campaign_id')
    })

    this.schema.createTable('affiliate_performance_history', (table) => {
      table.increments('id')
      table.integer('affiliate_id').unsigned().notNullable()
      table.enum('metric_type', ['earnings', 'conversions', 'referrals', 'tier_change']).notNullable()
      table.decimal('value', 15, 2).notNullable()
      table.string('period').notNullable()
      table.json('breakdown').nullable()
      table.json('metadata').nullable()
      table.timestamp('created_at')
      table.index('affiliate_id')
      table.index('metric_type')
      table.index('period')
    })
  }

  async down() {
    this.schema.dropTable('affiliate_performance_history')
    this.schema.dropTable('recruitment_metrics')
    this.schema.dropTable('affiliate_rewards')
    this.schema.dropTable('tier_promotions')
    this.schema.dropTable('affiliate_tiers')
    this.schema.dropTable('recruitment_campaigns')
    this.schema.dropTable('affiliate_referrals')
    this.schema.dropTable('referral_codes')
    this.schema.dropTable('affiliate_profiles')
  }
}
