import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('amazon_stores', (table) => {
      table.increments('id')
      table.integer('vendor_id').unsigned().notNullable().unique()
      table.string('seller_id').notNullable().unique()
      table.text('access_token').notNullable()
      table.text('refresh_token').nullable()
      table.string('region').defaultTo('us-east-1')
      table.json('scopes').defaultTo('[]')
      table.boolean('is_connected').defaultTo(false)
      table.enum('connection_status', ['disconnected', 'connecting', 'connected', 'error']).defaultTo('disconnected')
      table.timestamp('last_sync_at').nullable()
      table.timestamp('last_campaigns_sync_at').nullable()
      table.integer('sync_frequency').unsigned().defaultTo(60)
      table.boolean('auto_sync').defaultTo(true)
      table.integer('total_campaigns').unsigned().defaultTo(0)
      table.decimal('total_ad_spend', 10, 2).defaultTo(0)
      table.decimal('total_sales', 10, 2).defaultTo(0)
      table.string('currency', 3).defaultTo('USD')
      table.json('store_settings').nullable()
      table.json('error_log').nullable()
      table.timestamp('last_error_at').nullable()
      table.string('last_error_message').nullable()
      table.timestamp('connected_at').nullable()
      table.timestamp('disconnected_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('vendor_id').references('id').inTable('users').onDelete('CASCADE')
      table.index('vendor_id')
      table.index('seller_id')
      table.index('connection_status')
    })

    this.schema.createTable('amazon_campaigns', (table) => {
      table.increments('id')
      table.integer('amazon_store_id').unsigned().notNullable()
      table.string('campaign_id').notNullable()
      table.string('name').notNullable()
      table.enum('campaign_type', ['sponsorProducts', 'sponsorBrands', 'sponsorDisplay']).notNullable()
      table.enum('status', ['enabled', 'paused', 'archived']).defaultTo('enabled')
      table.decimal('daily_budget', 10, 2).nullable()
      table.decimal('total_spend', 10, 2).defaultTo(0)
      table.decimal('total_sales', 10, 2).defaultTo(0)
      table.decimal('acos', 5, 2).defaultTo(0)
      table.decimal('roas', 8, 2).defaultTo(0)
      table.integer('impressions').unsigned().defaultTo(0)
      table.integer('clicks').unsigned().defaultTo(0)
      table.decimal('ctr', 5, 2).defaultTo(0)
      table.decimal('cpc', 8, 2).defaultTo(0)
      table.integer('conversions').unsigned().defaultTo(0)
      table.decimal('conversion_rate', 5, 2).defaultTo(0)
      table.timestamp('start_date').nullable()
      table.timestamp('end_date').nullable()
      table.boolean('synced_to_hub').defaultTo(false)
      table.timestamp('last_synced_at').nullable()
      table.json('raw_data').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('amazon_store_id').references('id').inTable('amazon_stores').onDelete('CASCADE')
      table.index('amazon_store_id')
      table.index('campaign_id')
      table.index('status')
    })
  }

  async down() {
    this.schema.dropTable('amazon_campaigns')
    this.schema.dropTable('amazon_stores')
  }
}
