import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('kyc_submissions', (table) => {
      table.increments('id')
      table.integer('user_id').unsigned().notNullable()
      table.enum('submission_type', ['individual', 'business']).notNullable()
      table.enum('status', ['pending', 'under_review', 'verified', 'rejected', 'expired']).defaultTo('pending')
      table.integer('verification_level').defaultTo(1)
      table.string('first_name').nullable()
      table.string('last_name').nullable()
      table.date('date_of_birth').nullable()
      table.string('nationality', 5).nullable()
      table.enum('document_type', ['passport', 'drivers_license', 'national_id', 'business_registration']).nullable()
      table.string('document_number').nullable()
      table.datetime('expiry_date').nullable()
      table.string('business_name').nullable()
      table.string('business_registration').nullable()
      table.text('business_address').nullable()
      table.string('business_type').nullable()
      table.json('beneficiary_owners').nullable()
      table.string('source_of_funds').nullable()
      table.decimal('expected_annual_volume', 15, 2).nullable()
      table.string('country', 5).nullable()
      table.string('state').nullable()
      table.string('city').nullable()
      table.string('zip_code').nullable()
      table.integer('risk_score').defaultTo(0)
      table.enum('risk_level', ['low', 'medium', 'high', 'critical']).defaultTo('low')
      table.enum('compliance_status', ['compliant', 'non_compliant', 'requires_review']).defaultTo('requires_review')
      table.text('rejection_reason').nullable()
      table.text('notes').nullable()
      table.datetime('verified_at').nullable()
      table.datetime('next_review_date').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.index('user_id')
      table.index('status')
      table.index('risk_level')
      table.index('compliance_status')
    })

    this.schema.createTable('document_verifications', (table) => {
      table.increments('id')
      table.integer('kyc_submission_id').unsigned().notNullable()
      table.enum('document_type', ['proof_of_identity', 'proof_of_address', 'business_license', 'tax_certificate', 'beneficial_owner', 'bank_statement']).notNullable()
      table.text('document_url').notNullable()
      table.string('file_name').notNullable()
      table.bigint('file_size').notNullable()
      table.string('mime_type').notNullable()
      table.enum('verification_status', ['pending', 'verified', 'rejected', 'unclear']).defaultTo('pending')
      table.json('ocr_extracted_data').nullable()
      table.integer('match_score').defaultTo(0)
      table.datetime('expiry_date_extracted').nullable()
      table.string('document_number_extracted').nullable()
      table.string('issue_country').nullable()
      table.boolean('manual_review_required').defaultTo(false)
      table.text('rejection_reason').nullable()
      table.text('verifier_notes').nullable()
      table.integer('verified_by').unsigned().nullable()
      table.datetime('verified_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('kyc_submission_id').references('kyc_submissions.id').onDelete('CASCADE')
      table.index('kyc_submission_id')
      table.index('verification_status')
    })

    this.schema.createTable('risk_assessments', (table) => {
      table.increments('id')
      table.integer('kyc_submission_id').unsigned().notNullable()
      table.enum('assessment_type', ['pep_check', 'sanctions_check', 'aml_check', 'business_check', 'behavioral_check']).notNullable()
      table.integer('risk_score').defaultTo(0)
      table.enum('risk_level', ['low', 'medium', 'high', 'critical']).defaultTo('low')
      table.boolean('is_match').defaultTo(false)
      table.text('match_details').nullable()
      table.enum('pep_status', ['no_match', 'potential_match', 'confirmed_match']).nullable()
      table.enum('sanctioned_status', ['no_match', 'potential_match', 'confirmed_match']).nullable()
      table.enum('aml_status', ['clean', 'warning', 'flagged']).nullable()
      table.json('business_risk_factors').nullable()
      table.json('behavioral_indicators').nullable()
      table.string('data_source').notNullable()
      table.string('external_check_id').nullable()
      table.json('external_check_result').nullable()
      table.boolean('review_required').defaultTo(false)
      table.text('reviewer_notes').nullable()
      table.integer('reviewed_by').unsigned().nullable()
      table.datetime('reviewed_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('kyc_submission_id').references('kyc_submissions.id').onDelete('CASCADE')
      table.index('kyc_submission_id')
      table.index('assessment_type')
      table.index('risk_level')
    })

    this.schema.createTable('compliance_checks', (table) => {
      table.increments('id')
      table.integer('kyc_submission_id').unsigned().notNullable()
      table.enum('check_type', ['document_validity', 'age_verification', 'address_verification', 'business_legitimacy', 'beneficial_owner_check', 'source_of_funds']).notNullable()
      table.enum('check_status', ['pending', 'passed', 'failed', 'requires_review']).defaultTo('pending')
      table.text('compliance_result').notNullable()
      table.text('failure_reason').nullable()
      table.boolean('required_evidence_provided').defaultTo(true)
      table.json('evidence_details').nullable()
      table.string('regulatory_requirement').nullable()
      table.decimal('threshold_value', 12, 2).nullable()
      table.decimal('actual_value', 12, 2).nullable()
      table.enum('escalation_status', ['none', 'pending', 'escalated']).defaultTo('none')
      table.text('escalation_reason').nullable()
      table.integer('approved_by').unsigned().nullable()
      table.text('remarks').nullable()
      table.datetime('approved_at').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('kyc_submission_id').references('kyc_submissions.id').onDelete('CASCADE')
      table.index('kyc_submission_id')
      table.index('check_type')
      table.index('check_status')
    })

    this.schema.createTable('kyc_audit_logs', (table) => {
      table.increments('id')
      table.integer('kyc_submission_id').unsigned().nullable()
      table.integer('user_id').unsigned().notNullable()
      table.enum('action', [
        'submission_created',
        'document_uploaded',
        'verification_started',
        'verification_completed',
        'risk_assessment_completed',
        'compliance_check_passed',
        'compliance_check_failed',
        'status_changed',
        'approval_granted',
        'rejection_issued',
        'manual_review_requested',
        'appeal_submitted',
      ]).notNullable()
      table.enum('action_type', ['kyc_submission', 'document_verification', 'risk_assessment', 'compliance_check', 'workflow']).notNullable()
      table.enum('entity_type', ['kyc_submission', 'document', 'risk_assessment', 'compliance_check']).notNullable()
      table.integer('entity_id').unsigned().notNullable()
      table.string('previous_status').nullable()
      table.string('new_status').notNullable()
      table.integer('performed_by').unsigned().nullable()
      table.string('performed_by_role').notNullable()
      table.string('ip_address').nullable()
      table.text('user_agent').nullable()
      table.text('description').notNullable()
      table.json('metadata').nullable()
      table.enum('result', ['success', 'failure', 'pending']).defaultTo('pending')
      table.integer('duration').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
      table.foreign('kyc_submission_id').references('kyc_submissions.id').onDelete('CASCADE')
      table.foreign('user_id').references('users.id').onDelete('CASCADE')
      table.index('kyc_submission_id')
      table.index('user_id')
      table.index('action')
      table.index('created_at')
    })
  }

  async down() {
    this.schema.dropTable('kyc_audit_logs')
    this.schema.dropTable('compliance_checks')
    this.schema.dropTable('risk_assessments')
    this.schema.dropTable('document_verifications')
    this.schema.dropTable('kyc_submissions')
  }
}
